package:
  name: qmp
  version: "0.10"

source:
  git_rev: 0.10
  git_url: https://github.com/maurergroup/qm_playground.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python


about:
  home: warwick.ac.uk/maurergroup
  license: GPL3.0
  license_file: LICENSE
